# Generated by Django 3.2.6 on 2021-09-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_project_app', '0002_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='place_id',
        ),
    ]
