# Generated by Django 2.2 on 2021-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project_app', '0003_remove_business_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='place_id',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
